name: '이슈 생성'
description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: [feat]
title: '이슈 이름을 작성해주세요'
body:
  - type: dropdown
    id: assignee
    attributes:
      label: '🧑‍💻 담당자 선택 (GitHub ID)'
      description: '담당할 팀원의 GitHub 계정을 선택해주세요'
      multiple: false
      options:
        - endorsement0912
        - test
    validations:
      required: true

  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업 (Epic Number)'
      description: '상위 작업의 Epic Number를 기입해주세요 (EA3-Epic Number)'
      placeholder: 'EA3-Epic Number'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🌿 브랜치명 (Branch)'
      description: '이슈와 관련된 브랜치명을 작성해주세요 (타입명/EA3-Task_number-기능명)'
      placeholder: '타입명/EA3-Task number-기능명'
    validations:
      required: true


  - type: dropdown
    id: label-selection
    attributes:
      label: '🏷️ 라벨 선택 (Label)'
      description: '이슈의 성격에 맞는 라벨을 선택해주세요'
      multiple: false
      options:
        - feat
        - fix
        - docs
        - style
        - refactor
        - test
        - chore
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: '📌 이슈 설명 (Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '📋 작업 목록 (Tasks)'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
